# Generated by Django 4.0.3 on 2022-03-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='dep',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='EmployeeInfo',
        ),
    ]
